### ISSUE TITLE
Grammatical errors

### ISSUE THREAD

**Issue by NdagiStanley** [uranusjr/uranusjr.com#34]
### Expected behaviour

Hi @uranusjr, pardon me for this unsolicited feedback. I like your blog and while perusing, I noticed two tiny grammatical errors:

- [chronicle](https://github.com/uranusjr/uranusjr.com/blob/master/pages/fixtures/initial_data.json#L60) instead of **chronological**
- [Tutoria](https://github.com/uranusjr/uranusjr.com/blob/master/works/fixtures/initial_data.json#L219) instead of ** Tutorial** 

These are visible on these pages respectively

- https://uranusjr.com/
- https://uranusjr.com/work/

**Comment by uranusjr** [comment]
Thanks for catching them! This also reminds me I should update the work page to include more up-to-date information 🙂

**Comment by uranusjr** [comment]
Fixed!
